### ISSUE TITLE
 the blspec layout doesn't consider /etc/kernel/entry-token

### ISSUE THREAD

**Issue by MeisterP** [projg2/eclean-kernel#35]
I recently installed gentoo and it comes with `/etc/kernel/entry-token` set to `gentoo`.  In this case, `machine-id` is replaced by `gentoo` and kernels end up in directories like `/boot/gentoo/6.1.8-gentoo-dist/{linux, initrd}`

**Comment by mgorny** [comment]
Feel like making a pull request?

**Comment by MeisterP** [comment]
> Feel like making a pull request?

My python knowledge is very basic. I don't think I can find a suitable solution.

**Comment by mgorny** [comment]
Yeah, don't worry, I'll try to take a look at it in a few days.

**Comment by mgorny** [comment]
I'm sorry it took this long but I've finally enabled it on my system and implemented it. I think it works correctly, please let me know if you have any further issues (unfortunately, EK is currently broken on my system since I used EFI stub kernels).
